name: Verify Windows RCE
on: [push, workflow_dispatch] # push yapınca veya manuel tetikleyince çalışır

jobs:
  exploit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Exploit PoC
        run: python exploit_poc.py
